test-threads_1: test-threads_1.c
	gcc -o test-threads_1 test-threads_1.c -lpthread

test-threads_2: test-threads_2.c
	gcc -o test-threads_2 test-threads_2.c -lpthread

test-threads_3: test-threads_3.c
	gcc -o test-threads_3 test-threads_3.c -lpthread

test-threads_4: test-threads_4.c
	gcc -o test-threads_4 test-threads_4.c -lpthread

exercise-8-serial: exercise-8-serial.c
	gcc -o exercise-8-serial exercise-8-serial.c -g -lpthread

clean:
	rm -f test-threads_1 test-threads_2 test-threads_3 test-threads_4 exercise-8-serial