# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balls.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61lls.proto\"9\n\x15\x62\x61ll_draw_display_msg\x12\n\n\x02\x63h\x18\x01 \x02(\x0c\x12\t\n\x01x\x18\x02 \x02(\r\x12\t\n\x01y\x18\x03 \x02(\r\"A\n\x0epayperview_req\x12\x13\n\x0b\x63lient_name\x18\x01 \x02(\t\x12\x1a\n\x12\x63redit_card_number\x18\x02 \x02(\t\"(\n\x0fpayperview_resp\x12\x15\n\rrandom_secret\x18\x01 \x02(\r\"#\n\x15\x63lient_connection_req\x12\n\n\x02\x63h\x18\x01 \x02(\x0c\"-\n\x0cmovement_req\x12\n\n\x02\x63h\x18\x01 \x02(\x0c\x12\x11\n\tdirection\x18\x02 \x02(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'balls_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BALL_DRAW_DISPLAY_MSG']._serialized_start=15
  _globals['_BALL_DRAW_DISPLAY_MSG']._serialized_end=72
  _globals['_PAYPERVIEW_REQ']._serialized_start=74
  _globals['_PAYPERVIEW_REQ']._serialized_end=139
  _globals['_PAYPERVIEW_RESP']._serialized_start=141
  _globals['_PAYPERVIEW_RESP']._serialized_end=181
  _globals['_CLIENT_CONNECTION_REQ']._serialized_start=183
  _globals['_CLIENT_CONNECTION_REQ']._serialized_end=218
  _globals['_MOVEMENT_REQ']._serialized_start=220
  _globals['_MOVEMENT_REQ']._serialized_end=265
# @@protoc_insertion_point(module_scope)
