all: ncurses-example-1 ncurses-example-2

ncurses-example-1: ncurses-example-1.c
	gcc -g -o ncurses-example-1 ncurses-example-1.c -lncurses

ncurses-example-2: ncurses-example-2.c
	gcc -g -o ncurses-example-2 ncurses-example-2.c -lncurses

clean:
	rm -rf ncurses-example-1 ncurses-example-2 *.dSYM